language: node_js

node_js: '6.10'

install: npm install

script:
  - pwd
  - npm run test && npm run coverage

before_deploy:
  - npm run build

deploy:
  provider: "lambda"
  function_name: "cognicity-notification-lambda"
  region: ${env:AWS_REGION_US}
  role:
  runtime: "nodejs6.10"
  handler_name: "bin/functions/notify/index.default"
  environment_variables:
    - AWS_REGION: ${env:AWS_REGION_US}
    - AWS_SNS_ACCOUNT_ID: ${env:AWS_SNS_ACCOUNT_ID_US}
