language: node_js

node_js: '6.10'

install: npm install

script:
  - pwd
  - npm run test && npm run coverage

before_deploy:
  - npm run build

deploy:
  provider: "lambda"
  function_name: "cognicity-notification-lambda"
  region: $AWS_REGION_US
  role: $AWS_LAMBDA_ROLE_US
  runtime: "nodejs6.10"
  module_name: "functions/notify/index"
  handler_name: "default"
  environment_variables:
    - AWS_REGION: $AWS_REGION_US
    - AWS_SNS_ACCOUNT_ID: $AWS_SNS_ACCOUNT_ID_US
